# Задача на 2-ом шаге урока

**🧠 Практика по apply() на 3 столбцах**

Датасет для тестирования:

In [17]:
def create_phone_number(n):
    return(f'({n[:3]}) {n[4:7]}-{n[7:10]}')

In [19]:
n = [2, 4, 0, 100, 4, 11, 2602, 36]

In [20]:
sum(n)

2759

Задание: Создайте в df новый столбец final_ride_cost, который будет зависеть от рейтинга (rating) и максимальной скорости (speed_max) поездки. Значения в этом столбце будут отличаться в зависимости от двух условий:
- Если рейтинг выше 6 и максимальная скорость поездки меньше 120 км/ч, то стоимость поездки (ride_cost) уменьшите на 5%.
- В противном случае: стоимость поездки (ride_cost) увеличьте на 5%.

В новом столбце final_ride_cost отбросьте дробную часть значений, оставьте только целую часть. Так как стоимость измеряется в рублях, дробная часть не имеет значения.

In [1]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_2.csv')

# В столбце true_final_ride_cost записаны правильные ответы.
# Создайте столбец final_ride_cost исходя из условий задачи.

In [4]:
function = lambda x: x['ride_cost'] * 0.95 if x['rating'] > 6 and x['speed_max'] < 120 else x['ride_cost'] * 1.05

In [8]:
df['final_ride_cost'] = df.apply(function,axis=1).astype(int)
df.head()

,user_id,rating,speed_max,ride_cost,true_final_ride_cost,final_ride_cost
0,J19512539T,6.73,78.000000,4934,4687,4687
1,B22315336q,7.46,72.000000,235,223,223
2,y82944196A,4.86,168.181029,63835,67026,67026
3,G66226901h,7.70,74.000000,780,741,741
4,V24342105N,1.09,127.000000,891,935,935

In [6]:
# Корректность своего ответа можно проверить, например, таким образом
print(df['final_ride_cost'].equals(df['true_final_ride_cost']))

False

На вход подается: Переменная df  с полным DataFrame с исходными данными.
На выходе принимается: Измененный DataFrame (переменная df).

# Задача на 3-ем шаге урока

**🧠 Задача: 🖐 gold фичей**

Задача:

Создайте новый датафрейм, в котором для каждой машины есть следующие столбцы:

- Столбец feature_1 - Количество уникальных значений остановок (stop_times).
- Столбец feature_2 - Второй максимум столбца максимальной скорости (speed_max).
- Столбец feature_3 - Отношение минимального и максимального значения рейтинга.
- Столбец feature_4 - Самое популярное значение числа остановок (другим словами, мода).
- Столбец feature_5 - Стандартное отклонение стоимостей поездок (ride_cost).

Решение запишите в переменную result.

In [21]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_3.csv')

# В переменной ans находится правильный ответ для df
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_3_ans.csv')

In [ ]:
# Создайте новый датафрейм, в котором для каждой машины есть следующие столбцы:

# Столбец feature_1 - Количество уникальных значений остановок (stop_times).
# Столбец feature_2 - Второй максимум столбца максимальной скорости (speed_max-1).
# Столбец feature_3 - Отношение минимального и максимального значения рейтинга.
# Столбец feature_4 - Самое популярное значение числа остановок (другим словами, мода).
# Столбец feature_5 - Стандартное отклонение стоимостей поездок (ride_cost).
# Решение запишите в переменную result.
result = df.groupby("car_id", as_index=False).agg(feature_1=("stop_times", "nunique"),
                                                   feature_2=("speed_max", lambda x: x.nlargest(2).iloc[1]),
                                                   feature_3=("rating", lambda x: max(x) / min(x)),
                                                   feature_4=("stop_times", moda),
                                                   feature_5=("ride_cost", std))

In [26]:
my_func = lambda x: int(max(x) - min(x))  # Можно использовать свои собственные функции
result = df.groupby("car_id", as_index=False).agg(feature_1=("stop_times", "unique"),
                                                   feature_2=("speed_max", lambda x: x.nlargest(2).iloc[1]),
                                                   feature_3=("rating", lambda x: max(x) / min(x)),
                                                   feature_4=("stop_times", lambda x: x.mode()[0]),
                                                   feature_5=("ride_cost", 'std'))


# Смотрим результаты
result.head(5)

,car_id,feature_1,feature_2,feature_3,feature_4,feature_5
0,G-1056464Y,"[1, 3, 0, 14, 2]",96.000000,3.341365,1,125833.828153
1,M15952724y,"[1, 0, 2, 3]",151.000000,18.300000,0,26887.711194
2,M50269450O,"[0, 2, 6, 3, 8, 1, 14, 4]",115.597945,4.141631,0,136560.952417
3,Z16920973J,"[2, 0, 1, 3]",94.167306,4.611429,0,65036.154948
4,q-1127410X,"[2, 0, 1]",137.914456,9.055556,0,90794.737314

In [ ]:
# result =

На вход подается: Переменная df  с исходными данными.
На выходе принимается: Переменная result.

# Задача на 4-ом шаге урока

**🧠 Задача на merge()**

Задача:
- Обогатите датасет rides про поездки информацией о будущем виде поломки, используя датасет cars.
- Удалите лишние столбцы. Таблицу rides надо дополнить лишь столбцом target_class.
- Удалите поездки, для которых нет информации про поломки.  
- Запишите в переменную result.

In [27]:
import pandas as pd

rides = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_4_rides.csv')
cars = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_4_cars.csv')

# В переменную ans записан правильный ответ, с которым можно сверить свое решение.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_4_ans.csv')

In [29]:
ans.head()

       car_id ride_id  rating  ride_duration  ride_cost     target_class
0  L-1156474z     u1g    5.81             33        391        break_bug
1  M20797256F     e1V    5.01             56        667  engine_overheat
2  E16896376o     B1Q    4.88             26        228  engine_overheat
3  X10754765V     M1i    1.62             29        312      electro_bug
4  E16896376o     V1L    6.98             37        512  engine_overheat

In [36]:
# Задача:

# Обогатите датасет rides про поездки информацией о будущем виде поломки, используя датасет cars.
# Удалите лишние столбцы. Таблицу rides надо дополнить лишь столбцом target_class.
# Удалите поездки, для которых нет информации про поломки.
# Запишите в переменную result.
result = rides.merge(cars[['target_class','car_id']], on='car_id', how='right')

In [33]:
# Задача:

# Обогатите датасет rides про поездки информацией о будущем виде поломки, используя датасет cars.
# Удалите лишние столбцы. Таблицу rides надо дополнить лишь столбцом target_class.
# Удалите поездки, для которых нет информации про поломки.
# Запишите в переменную result.

result = rides.merge(cars, on='car_id', how='left')[['ride_id', 'car_id', 'rating', 'ride_duration', 'ride_cost', 'target_class']].dropna()
result.head()

   ride_id      car_id  rating  ride_duration  ride_cost     target_class
7      u1g  L-1156474z    5.81             33        391        break_bug
17     e1V  M20797256F    5.01             56        667  engine_overheat
18     B1Q  E16896376o    4.88             26        228  engine_overheat
21     M1i  X10754765V    1.62             29        312      electro_bug
28     V1L  E16896376o    6.98             37        512  engine_overheat

На выходе принимается: Переменная result

In [ ]:
# result =

# Задача на 5-ом шаге урока

**🧠 Задача на transform() и 3 silver фичи**

На вход подается: Переменная rides с исходными данными про поездки.

Задача:

- Обогатите датасет rides про поездки дополнительными признаками без использования метода merge.
- Добавьте столбец car_ride_count - общее число поездок для этой машины.
- Добавьте столбец user_rating_max - максимальный рейтинг, поставленный этим пользователем.
- Добавьте столбец user_ride_cost_mean - средняя стоимость поездки этого пользователя.
- Результат запишите в переменную result.

In [37]:
import pandas as pd

rides = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_5.csv')

# В столбцах true_car_ride_count, true_user_rating_max, true_user_ride_cost_mean записаны правильные ответы.
# Создайте столбцы car_ride_count, user_rating_max, user_ride_cost_mean

In [ ]:
# Проверить корректность своего решения можно, например, таким способом
print(rides['true_car_ride_count'].equals(rides['car_ride_count']))
print(rides['true_user_rating_max'].equals(rides['user_rating_max']))
print(rides['true_user_ride_cost_mean'].equals(rides['user_ride_cost_mean']))

На выходе принимается: Переменная result.

In [ ]:
# result =

# Задача на 6-ом шаге урока

**🧠 Задача на transform() и 4 самописные функции**

На вход подается: Переменная rides  с исходными данными про поездки.

Задача

- Обогатите датасет rides про поездки дополнительными признаками без использования метода merge.
- Добавьте столбец feature_1 — 75% перцентиль столбца ride_cost для каждого пользователя (user_id).
- 🎃 Добавьте столбец feature_2 — разницу максимального и минимального значения rating, деленную на среднее столбца rating для каждого пользователя (user_id).
- 👽 Добавьте столбец feature_3  — количество значений ride_duration, которое больше 40 для каждой машины (car_id).
- 👾 Добавьте столбец feature_4 — сумму значений ride_duration, которая больше 40 для каждой машины (car_id).
- Результат запишите в переменную result.

In [ ]:
import pandas as pd

rides = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_6.csv')

# В столбцы true_feature_1, true_feature_2, true_feature_3, true_feature_4 записаны правильные ответы
# Создайте столбцы feature_1, feature_2, feature_3, feature_4.

In [ ]:
# Проверить корректность своего решения можно, например, таким способом
print(rides['true_feature_1'].equals(rides['feature_1']))
print(rides['true_feature_2'].equals(rides['feature_2']))
print(rides['true_feature_3'].equals(rides['feature_3']))
print(rides['true_feature_4'].equals(rides['feature_4']))

На выходе принимается: Переменная result

In [ ]:
# result =

# Задача на 7-ом шаге урока

**🧠 Задача на pivot_table() и merge()**

Задача. На основе этого датафрейма надо будет собрать несколько сводных таблиц (pivot table) и потом смержить их в одну итоговую, получив некое подобие эмбеддингов для подачи в модель.

- Индексом во всех таблицах будет user_id.
- 🙂 Первая таблица: Сколько раз пользователь брал машины определенного класса?
- 🙃 Вторая таблица: Какими были максимальная, минимальная и средняя дистанция и стоимость поездки пользователя?
- 🙂 Третья таблица: Сколько уникальных машин брал пользователь в аренду?
- Далее соединяем по ключу (смерживаем) все 3 таблицы в одну.
- И в конце добавляем бинарный таргет в столбец crazy_driver: Является ли наш пользователь безумным гонщиком? Если его максимальная скорость превышала 100 км/ч, то 1; если не превышала, то 0.
- Результат решения запишите в переменную result.

In [ ]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_7.csv')

# В ans записан правильный ответ
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_7_ans.csv')

In [ ]:
# result =

Результат решения запишите в переменную result

Комментарий: Не забывайте избавляться от мультииндекса и использовать pivot_table. Использовать groupby нельзя! Пропуски заполнять 0.